package com.suntec.retail.commonEnums;

public enum MechanismType {
    FIXED_REBATE,
    PROGRESSIVE_REBATE_LEVEL1,
    PROGRESSIVE_REBATE_LEVEL2,
    PROGRESSIVE_REBATE_LEVEL3,
    PRIMARY_VISIBILITY_REBATE,
    SDA,
    PROMOTION_ACTIVITIES,
    LISTING_FEE,
    RANGE_MANAGEMENT,
    LOYALTY_REBATE,
    NO_RETURNING_FEE,
    FIXED_RENTALS,
    DATA_SHARING_FEE,
    LOGISTICS_REBATE,
    MERCHANDISER_CHARGE,
    NEW_STORE_OPENING_FEE,
    NATIONAL_PROMOTION_FEE,
    TOTAL_BACK_MARGIN,
    FRONT_MARGIN
}
